# string
nilai = [
["BANANA", "JERUK", "MANGGA","ALWAN"],
["DURIAN", "APEL", "SEMANGKA","NADIF"],
["PISANG", "NANAS", "SALAK","FAISAL"],
["ANGGUR", "LECI", "JAMBU","DIMAS"],
["STROBERI", "MELON", "KURMA","REZA"]
]   
print (nilai[2][3])
nilai_2 =[

# angka
[77, 100, 200,21],
[55, 90, 100, 19],
[7, 10, 20, 2],
[9, 15, 30, 4],
[8, 12, 25, 3]
]
print (nilai_2[3][2])

#study case
buah_cabang = [
["BANANA", "JERUK", "MANGGA",],
["cabang 1", "cabang 2", "cabang 3"]
]
print (buah_cabang[0][2])
print (buah_cabang[1][0])
stok = [
[33, 45, 20],
[55, 60, 25],
]
print (stok[1][2])


print ("==================STUDY CASE==================")