print("==============INFORMASI RESTORAN================")
restoran= input("nama restoran:")
jenis_makanan= input("jenis makanan:")
restoran_buka=bool(input("restoran buka jam berapa:"))
print(f"restoran buka pada jam: {restoran_buka}")
rating_makanan=float(input("rating makanan:"))
print(f"rating makanan anda adalah: {rating_makanan}")

print("==============DATA PESANAN================")

nama_pelanggan= input("nama pelanggan:")
nomor_meja=int(input("nomor meja:"))
nama_makanan= input("nama makanan:")
jumlah_pesanan=int(input("jumlah pesanan:"))

print("==============TIPE DATA================")
print("tipe data restoran:",type(restoran))
print("tipe data jenis makanan:",type(jenis_makanan))
print("tipe data restoran buka:",type(restoran_buka))
print("tipe data rating makanan:",type(rating_makanan))
print("tipe data nama pelanggan:",type(nama_pelanggan))
print("tipe data nomor meja:",type(nomor_meja))
print("tipe data nama makanan:",type(nama_makanan))
print("tipe data jumlah pesanan:",type(jumlah_pesanan))
